### ISSUE TITLE
package level classes are ignored 

### ISSUE THREAD

**Issue by mgenov** [sonatype/jarjar-maven-plugin#2]
Hello, 

It seems that there is some kind of issue when private classes are used. In my case I'm trying to jarjar sitebricks library which is using class named SitebricksInternalModule in class named SitebricksModule. Here is the include definition: 

``` XML
<include>com.google.sitebricks:sitebricks</include>
<include>com.google.sitebricks:sitebricks-converter</include>
<include>com.google.sitebricks:sitebricks-client</include>
<include>com.google.sitebricks:sitebricks-annotations</include>
```

and here is a list of packed classes: 
pwd
myapp/target/temp/com/google/sitebricks

mgenov:sitebricks(master!) $ ls -alh Sitebricks_Module_.class
-rw-r--r--@ 1 mgenov  staff   668B Mar 19 18:23 SitebricksModule$1.class
-rw-r--r--@ 1 mgenov  staff   785B Mar 19 18:23 SitebricksModule$2.class
-rw-r--r--@ 1 mgenov  staff   719B Mar 19 18:23 SitebricksModule$3.class
-rw-r--r--@ 1 mgenov  staff   719B Mar 19 18:23 SitebricksModule$4.class
-rw-r--r--@ 1 mgenov  staff   1.4K Mar 19 18:23 SitebricksModule$5.class
-rw-r--r--@ 1 mgenov  staff   3.0K Mar 19 18:23 SitebricksModule$6.class
-rw-r--r--@ 1 mgenov  staff   1.3K Mar 19 18:23 SitebricksModule$BindingKind.class
-rw-r--r--@ 1 mgenov  staff   1.2K Mar 19 18:23 SitebricksModule$LinkingBinder$1.class
-rw-r--r--@ 1 mgenov  staff   5.5K Mar 19 18:23 SitebricksModule$LinkingBinder.class
-rw-r--r--@ 1 mgenov  staff   9.7K Mar 19 18:23 SitebricksModule.class
-rw-r--r--@ 1 mgenov  staff   1.2K Mar 19 18:23 SitebricksServletModule.class
-rw-r--r--@ 1 mgenov  staff   1.5K Mar 19 18:23 SitebricksServletSupportModule.class

where the temp folder contains the extracted jar content. As it looks the SitebricksInternalModule is missing. 

Using revision 218fa49ba1

**Comment by mcculls** [comment]
Is the class using Java6 bytecode? If so then it might be http://code.google.com/p/jarjar/issues/detail?id=20 which we could try to patch locally

**Comment by mcculls** [comment]
I've updated the patched JarJar code, can you retry with the latest from master?

**Comment by mgenov** [comment]
As it seems sitebricks is using 1.6, and probably the issue is same. 

``` XML
  <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>2.3.2</version>
        <configuration>
          <source>1.6</source>
          <target>1.6</target>
        </configuration>
      </plugin>
```

Sure. I'll try to find out where it solves the issue.

**Comment by mgenov** [comment]
The last commit fixes the issue. Great job :)

**Comment by mcculls** [comment]
Cool, I'll sort out a new release of the plugin

**Comment by mgenov** [comment]
btw, are there any plans for next release ?

**Comment by mcculls** [comment]
I've just deployed 1.6 which should appear on Maven central later today (can take a few hours for mirrors, etc. to sync up)

**Comment by mgenov** [comment]
Great. Thanks for the fast support :)
