### ISSUE TITLE
dependencies placed in XML file (logback.xml) are ignored

### ISSUE THREAD

**Issue by mgenov** [sonatype/jarjar-maven-plugin#5]
I'm encountering an issue which causes appenders of logback to not be packaged.

Here is how the appender is defined: 

``` XML
<appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
     <file>test-log.log</file>
     <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
       <!-- daily rollover -->
       <fileNamePattern>log/archive/test.%d{yyyy-MM-dd}.log</fileNamePattern>
       <!-- keep 5 days' worth of history -->
       <maxHistory>5</maxHistory>
     </rollingPolicy>
     <encoder>
       <pattern>%d{HH:mm:ss.SSS,Europe/Sofia} [%thread] %-5level %logger{35} - %msg%n</pattern>
     </encoder>
   </appender> 

```

I made a little hack to prevent this currently. In my entry point, I've added the following snippet: 

``` java
    RollingFileAppender ff = new RollingFileAppender();
    ff.equals("");

    TimeBasedRollingPolicy oo = new TimeBasedRollingPolicy();
    oo.equals("");
```

and things are working fine.

**Comment by mcculls** [comment]
jarjar only looks at references in the class bytecode, not XML, so it doesn't see this reference. To tell jarjar to keep the appender classes you can always add a keep instruction: `<keep pattern="ch.qos.logback.core.rolling.**"/>`

**Comment by mgenov** [comment]
Ah I see. 

It seems that it's not a problem, so I'm closing the issue.
